const newWords1 =
  'wide,part,mink,tummy,goods,nook,jelly,slow,tufts,cold,lane,son,same,much,deer,silk,cove,thing,try,duckling,mask,hike,car,rage,gift,very,last,well,mess,left,rush,gone,drill,meet,lid,lisp,post,bent,mice,rope,logs,hat,swim,read,upon,idea,singing,kites,feet,must,turning,wanted,sprung,zoomed,large,closed,plates,matching,track,chart,bread,clock,crusts,pain,loud,flapped,cell,cheese,beak,cog,poor,power,foam,clutch,knife,place,oil,gushed,china,stopped,also,floor,frames,studied,spikes,speech,shoe,prize,smug,rapids,slide,goals,shelter,creak,gutter,booth,frankly,knot,search,crouched,found,gloves,pretty,baskets,bonnet,rodeo,salad,cousin,camera,wrenches,goggles,inflate,single,polish,dolphin,skiing,Texas,mumble,direct,detail,alas,barrels,clerks,forty,embers,paddles,whiskers,condition,slumped,blurted,wallet,focus,circus,aware,mango,firmly,imagined,reveal,ached,fabric,detour,impolite,squiggles,because,teachers,ordinary,capture,feline,gusto,kitchen';

const newWords2 =
  'cleat,bustling,scarf,surface,Nile,scrolls,shimmery,indent,sitcom,detect,blindfolded,basically,squints,clobbered,relative,cringed,drone,rattled,indie,eyesore,playlist,throat,hull,outright,squabbling,scuba,trickster,glib,sneer,absent,texture,scuffle,irregular,savor,hedgehog,stoats,talons,inclined,wardrobe,revved,dire,masthead,vibrant,wizard,nudged,Leghorn,shrine,Jamestown,pineapple,crockery,gauze,exception,cavity,Neptune,notification,ogre,simplicity,lavished,archduke,dingoes,passersby,nada,Juneteenth,parsnips,curtains,adorned,loneliness,caverns,novice,invasions,dedicated,symbol,reduce,destination,ostriches,grudgingly,canopy,scrawny,classified,telescope,fidgeting,mulberry,surrounded,associated,furthermore,weird,dependable,summit,conkers,mutual,dormitories,tuxedo,decimal,alibi,orientation,inlaid,cobblestone,devious,sardine,contraption,technique,flaxen,triplicate,emboldened,Javas,biome,Wales,Avalon,corridor,cardigan,columns,cubicle,interjected,withered,cambric,hackles,faltered,Lincoln,granite,radiation,wattles,tartan,surveyed,emitting,preened,wretched,contorted,charlotte,elation,expanse,chai,metropolis,mousse,contessa,acutely,granules,pedestals,wreaked,renowned,colleagues,invigorating,sudoku,dutifully,mournful,professional,exerts,arid,deceptively,sustenance';

const newWords3 =
  'reflexology,intentionally,cocoon,motley,fetlocks,ranchero,intolerance,gluten,pulverized,mystified,swankiest,clouting,demeanor,mallet,Singapore,disembodied,Korea,aisles,unsportsmanlike,ensnarement,morbidity,proctors,trodden,torturous,referral,aerials,surgeon,Judaism,stalemate,thoroughfare,transgressions,abdomen,appeasement,liability,penchant,propensity,instinctive,infectious,Minnesota,adversity,convictions,intestine,discriminating,exile,lineage,coaxing,permanence,larkspur,drudgery';

// const newWords4 =
//   'knack,satisfactory,barefoot,trope,knock,whittle,joyful,genuine,recluse,shield,tiger,romaine,migraine,oasis,navigator,humane,polenta,delicacy,noggin,background,thistle,althorn,Spaniel,kilt,whirlybird,Hungary,welding,aforesaid,varnish,spindle,wheedle,whelp,yonder,riffraff,restive,various,giggle,bowie,teemed,soppiness,bask,lateral,usher,prone,selfie,skydiving,memes,nuggets,frailty,sweltering,scrounge,praise,scripture,ulna,fellowship,amass,missive,jitterbug,kennel,heavenly,shindig,melody,membership,oblong,yammer,whereas,coercive,bailiff,infiltrate,skirmish,constituent,flounder,cleave,millionaire,concrete,slurry,heiress,reign,spectral,dialect,heist,avenue,pending,ewe,stagestruck,standee,sailage,yoo-hoo,profiteer,kernel,tawny,scalp,scrapple,nominee,martial,acumen,infirm,bleary,attitude,beseech,sunseeker,cornily,contraction,scooter,acceptance,rugby,shore,yippee,wand,Merlin,carnation,neaten,depose,frock,camcorder,gossip,version,fluid,vlogging,diversity,spangled,barbie,delta,handyman,stewardship,gruel,groom,trice,brick,privet,debunk,ballad,chide,atonement,citation,hardtack,rabid,teenagers,peat,harrowing,hobble,peddle,effortless,moped,groats,Highlands,retriever,anime,regiment,sterling,bootless,forgeable,transmissibility,gridiron,summoned,applicable,isms,tentacled,exude,bermudas,amusement,baptismal,postural,refrigerant,surly,scornfully,leaven,blurb,elasticity,quantify,redemption,zygote,lithium,docket,rubric,Hawaiian,pendragon,eggcorn,tabulate,cidery,puritan,caboodle,Godspeed,Thailand,pepita,lithophone,tai chi,parasol,screeno,provenance,ouster,Dudley,dicey,turken,riddance,repentant,manacle,Amish,unremitting,condiments,vaccination,floridly,obsolete,kodak';

// const newWords5 =
//   'terrarium,posterity,statusy,mambo,putrid,FLOTUS,insomnia,incompetent,Disneyfication,congeniality,intertidal,solitude,optician,gelatinous,gotcha,capitalist,respite,eighth,Shetland,causal,hologram,spiteful,snitch,maternity,bungee,periwinkle,entreat,peninsular,flipperling,fleeciness,escapade,handle,gumption,mortician,homesteader,nitrate,joinery,literally,medusa,unchristened,buzzworthy,recumbent,tiffany,musketeers,windbaggery,proposal,weaponry,deceitful,cinderella,league,repercussion,astounding,hijab,donatee,parvo,apparel,squeamish,Oceanian,charitable,physical';

const Arr = {
  level1: newWords1.split(','),
  level2: newWords2.split(','),
  level3: newWords3.split(','),
  // level4: newWords4.split(','),
  // level5: newWords5.split(','),
};

export default Arr;
