const newWords1 =
  'wide,part,mink,tummy,goods,nook,jelly,slow,tufts,cold,lane,son,same,much,deer,silk,cove,thing,try,duckling,mask,hike,car,rage,gift,very,last,well,mess,left,rush,gone,drill,meet,lid,lisp,post,bent,mice,rope,logs,hat,swim,read,upon,idea,singing,kites,feet,must,turning,wanted,sprung,zoomed,large,closed,plates,matching,track,chart,bread,clock,crusts,pain,loud,flapped,cell,cheese,beak,cog,poor,power,foam,clutch,knife,place,oil,gushed,china,stopped,also,floor,frames,studied,spikes,speech,shoe,prize,smug,rapids,slide,goals,shelter,creak,gutter,booth,frankly,knot,search,crouched,found,gloves,pretty,baskets,bonnet,rodeo,salad,cousin,camera,wrenches,goggles,inflate,single,polish,dolphin,skiing,Texas,mumble,direct,detail,alas,barrels,clerks,forty,embers,paddles,whiskers,condition,slumped,blurted,wallet,focus,circus,aware,mango,firmly,imagined,reveal,ached,fabric,detour,impolite,squiggles,because,teachers,ordinary,capture,feline,gusto,kitchen';

const newWords2 =
  'gradual,ferocious,frequently,permission,towel,sundae,ornament,rooster,scold,organza,fragile,galaxy,complaint,curries,tennis,grumbling,garlic,hula,reactionary,muscular,drizzle,accurate,studio,illusionist,genetic,levity,moisture,toughness,tasteless,astute,turtle,Pinkerton,fortune,sluggard,bedlam,shortfall,cowlick,opinionated,slogan,triumphant,parenthetic,listener,guardian,dwindled,fraught,sturdy,treadmill,originate,**forfend, OR forefend,eavesdrop,January,scruple,moxie,winnow,incentive,admirer,emotional,chia,raspberry,bogus,recoup,bookworm,veteran,erase,downcast,spinal,demolition,gargantuan,salsa,chaotic,shrimp,mandate,turret,pigeon,satellite,parasite,favorite,OR *favourite,cascade,dandelion,famous,pristine,golden,modesty,amphibian,jealousy,remedial,vouch,trivia,shoulder,zebra,butterscotch,apron,beagle,kidney,wistful,raven,fructose,Amazon,companion,panorama,gimmick,flannel,cucumber,McMansion,janitor,lionize,headdress,ludicrous,pear,system,pedigree,empty,amulet,guess,magician,carrot,meteor,distraught,freight,honeybee,blemish,crumpet,blizzard,squirm,harmonious,lawyer,valiant,purse,raisin,trumpet,bias,lettuce,shamrock,Americana,monopolize,water,marathon,omission,newbie,spreadsheet,badger,fortification,hydra,grouse,manta,astonish,fashionista,stubble,genius,nuance,stencil,penguin,freckle,blooper,misconception,lambkin,chowder,sunflower,lambasted,volumetric,flattery,simmer,whisk,bathtub,fantastically,failure,tolerable,mosquito,target,angora,snippet,ascribe,hodgepodge,verbiage,nephew,imbibe,savvy,reckon,boorish,tarmac,iteration,nurture,volcano,forensics,miraculous,trendy,permafrost,iceberg,cactus,nationalism,leeway,pilferer,rollicking,quart,lactose,domineering,onion,abandon,vault,junior,hamlet,jubilant';

const newWords3 =
  'thawed,uncle,dawdle,mogul,troll,kindred,tantrum,science,cement,venomous,plaintiff,mayhem,thicket,gymnastics,island,peacenik,ounce,memorandum,bother,missile,munchkin,banana,furnace,foothills,tongue,caterpillar,wasp,kudos,alpha,shebang,tibia,hazelnut,votive,storm,mince,bubbly,graham,headlong,timber,medallion,maximum,clover,casino,distinctive,mister,warning,useful,difficult,mischief,talent,kiwi,publish,mutter,sedentary,divine,lexicon,bristle,daresay,owlishly,criminal,recipient,strong,canteen,aviation,lucky,rocket,reflect,scent,puzzles,scumble,extinct,jersey,trapezoid,dillydally,haggle,sword,mastiff,cooperate,merchandise,melted,apology,carnival,buffoonery,intellectual,tickled,domino,ignite,legacy,splurge,neigh,cabbage,erode,formalize,OR *formalise,anyway,isolation,measly,apprehensive,zither,invoke,upshot,climate,Yankee,dim sum,moose,cuckoo,dilemma,outrageous,silver,fedora,wildcat,monstrosity,sofa,eggplant,kosher,minority,default,heroic,bombard,furtive,journal,tulip,myself,marine,cloudy,cricket,motto,torch,pamper,pleasant,robin,historical,rules,geometric,villa,midriff,teaspoon,worrywart,developer,shopaholic,magma,briefcase,deputy,mangrove,enfranchise,kiln,webisode,kangaroo,Romeo,emerge,twitchy,arrogant,normative,homework,mildew,pattern,coffee,botch,receptacle,bagpipe,bonfire,abruptly,bushel,skedaddle,toddler,everglades,pellet,klutz,envoy,postpone,wafer,software,factoid,marvelous,OR marvellous,evince,season,horizon,arborio,cartoon,dough,emperor,utterable,leniency,frivolous,potato,wholehearted,metadata,farewell,hypnotic,jewel,tangible,nourish,vulpine,aloha,entrance,kindergarten,restaurant,excavating,dodge,iota,gelato,hankering,esteem';

// const newWords4 =
//   'knack,satisfactory,barefoot,trope,knock,whittle,joyful,genuine,recluse,shield,tiger,romaine,migraine,oasis,navigator,humane,polenta,delicacy,noggin,background,thistle,althorn,Spaniel,kilt,whirlybird,Hungary,welding,aforesaid,varnish,spindle,wheedle,whelp,yonder,riffraff,restive,various,giggle,bowie,teemed,soppiness,bask,lateral,usher,prone,selfie,skydiving,memes,nuggets,frailty,sweltering,scrounge,praise,scripture,ulna,fellowship,amass,missive,jitterbug,kennel,heavenly,shindig,melody,membership,oblong,yammer,whereas,coercive,bailiff,infiltrate,skirmish,constituent,flounder,cleave,millionaire,concrete,slurry,heiress,reign,spectral,dialect,heist,avenue,pending,ewe,stagestruck,standee,sailage,yoo-hoo,profiteer,kernel,tawny,scalp,scrapple,nominee,martial,acumen,infirm,bleary,attitude,beseech,sunseeker,cornily,contraction,scooter,acceptance,rugby,shore,yippee,wand,Merlin,carnation,neaten,depose,frock,camcorder,gossip,version,fluid,vlogging,diversity,spangled,barbie,delta,handyman,stewardship,gruel,groom,trice,brick,privet,debunk,ballad,chide,atonement,citation,hardtack,rabid,teenagers,peat,harrowing,hobble,peddle,effortless,moped,groats,Highlands,retriever,anime,regiment,sterling,bootless,forgeable,transmissibility,gridiron,summoned,applicable,isms,tentacled,exude,bermudas,amusement,baptismal,postural,refrigerant,surly,scornfully,leaven,blurb,elasticity,quantify,redemption,zygote,lithium,docket,rubric,Hawaiian,pendragon,eggcorn,tabulate,cidery,puritan,caboodle,Godspeed,Thailand,pepita,lithophone,tai chi,parasol,screeno,provenance,ouster,Dudley,dicey,turken,riddance,repentant,manacle,Amish,unremitting,condiments,vaccination,floridly,obsolete,kodak';

// const newWords5 =
//   'terrarium,posterity,statusy,mambo,putrid,FLOTUS,insomnia,incompetent,Disneyfication,congeniality,intertidal,solitude,optician,gelatinous,gotcha,capitalist,respite,eighth,Shetland,causal,hologram,spiteful,snitch,maternity,bungee,periwinkle,entreat,peninsular,flipperling,fleeciness,escapade,handle,gumption,mortician,homesteader,nitrate,joinery,literally,medusa,unchristened,buzzworthy,recumbent,tiffany,musketeers,windbaggery,proposal,weaponry,deceitful,cinderella,league,repercussion,astounding,hijab,donatee,parvo,apparel,squeamish,Oceanian,charitable,physical';

	const Arr = {
    level1: newWords1.split(','),
    level2: newWords2.split(','),
    level3: newWords3.split(','),
  };

  export default Arr;